# --- Basic options --- #
title: Dept_Rental_System
description: 학과별 대여 및 물품 관리 시스템
author: JustBeaver

# 네비게이션 바 항목 수정
navbar-links:
  Home: "index"
  Request: "request"
  Inventory: "inventory"
  Status: "status"
  GitHub: "https://github.com/shinyugoan"

# 아바타 이미지 및 색상 유지

# --- Footer options --- #
social-network-links:
  email: "your_email@domain.com"
  github: shinyugoan

share-links-active:
  facebook: true
  linkedin: true

# Exclude 항목 수정 필요 없음
